services:
  reverseproxy:
    image: reverseproxy
    ports:
      - 80:80
      - 8080:8080
    restart: always
  nginx:
    depends_on:
      - reverseproxy
    image: nginx:latest
    restart: always
  apache:
    depends_on:
      - reverseproxy
    image: php:7.4-apache
    restart: always
