version: "3"
services:
  web:
    container_name: apache_server
    build:
      context: ./apache
    ports:
      - 8080:8080
      - 8081:8081
  proxy:
    container_name: nginx_proxy
    build:
      context: ./nginx
    ports:
      - 80:80
